### ISSUE TITLE
PHP PRoblem

### ISSUE THREAD

**Issue by dawidszyja** [Dr-Jekill/2Moons-2.0-php8#2]
Hello,
After installation I got problem:

 
--
Message: Creation of dynamic property Theme::$skininfo is deprecatedFile: /includes/classes/class.theme.phpLine: 25URL: http://ssssss/PHP-Version: 8.2.10PHP-API: litespeed2Moons Version: 2.0.0Debug Backtrace:#0 /includes/classes/class.theme.php(25): errorHandler(8192, 'Creation of dyn...', 'FILEPATH ...', 25)#1 /includes/common.php(73): Theme->__construct()#2 /index.php(24): require('FILEPATH ...')#3 {main}

is it mean that You do not rewrite it yet?

**Comment by yamilrh** [comment]
Añade arriba class Theme lo siguiente #[AllowDynamicProperties]
vas a necesitar hacer esto en muchos ficheros.
Saludos

**Comment by yamilrh** [comment]
Busca en el archivo class.theme.php
private $THEMESETTINGS; 
Añade luego
private $skininfo;
private $skin;
private $customtpls;

**Comment by Dr-Jekill** [comment]
Bug fixed in this update. Enjoy!
